name: "Build"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - name: Install cachix
      run: |
        nix-env -iA cachix -f https://cachix.org/api/v1/install
    - name: Use cachix nix-tools cache
      run: |
        cachix use nix-tools
    - name: Build
      run: |
        cachix use amarrella
        cachix push --watch-store amarrella &
        nix build -j auto -L -f . aws-lambda-haskell-runtime-client.components.tests
      env:
        CACHIX_SIGNING_KEY: '${{ secrets.CACHIX_SIGNING_KEY }}'
