name: "Build"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - run: cachix use nix-tools
    - uses: cachix/cachix-action@v2
      with:
        name: amarrella
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
